include:
  - ./docker-compose-base.yml

# To ensure that the container processes the locally modified `service_conf.yaml.template` instead of the one included in its image, you need to mount the local `service_conf.yaml.template` to the container.
services:
  deeprag:
    depends_on:
      mysql:
        condition: service_healthy
    image: ${DEEP_RAG_IMAGE}
    container_name: deeprag-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 8088:80
      - 443:443
      - 5678:5678
      - 5679:5679
    volumes:
      - ./deeprag-logs:/deeprag/logs
      - ./nginx/deeprag.conf:/etc/nginx/conf.d/deeprag.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../history_data_agent:/ragflow/history_data_agent
      - ./service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template

    env_file: .env
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
    networks:
      - ragflow
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"